spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest     #latest(default), earliest
  cloud:
    function:
      definition: publishMessage;
    stream:
      default:
#        contentType: application/json
        group: chat.presence
      bindings:
        publishMessage-out-0:
          destination: chat.api.message
        publishMessage-in-0:
          destination: chat.api.message
